BEGIN TRANSACTION;

DROP TABLE IF EXISTS sqlean_define;

DROP TRIGGER IF EXISTS ITP_UPDATE_FinsPériodes;
DROP TRIGGER IF EXISTS Variétés_UPDATE_FinsPériodes;

ALTER TABLE ITP ADD COLUMN S_semis INTEGER;
ALTER TABLE ITP ADD COLUMN S_plantation INTEGER;
ALTER TABLE ITP ADD COLUMN S_récolte INTEGER;
ALTER TABLE ITP ADD COLUMN D_récolte INTEGER;
ALTER TABLE ITP ADD COLUMN Décal_max INTEGER;

ALTER TABLE Variétés ADD COLUMN S_récolte INTEGER;
ALTER TABLE Variétés ADD COLUMN D_récolte INTEGER;

UPDATE ITP SET S_semis=1 WHERE Déb_semis='01-01';
UPDATE ITP SET S_semis=3 WHERE Déb_semis='01-15';
UPDATE ITP SET S_semis=5 WHERE Déb_semis='02-01';
UPDATE ITP SET S_semis=7 WHERE Déb_semis='02-15';
UPDATE ITP SET S_semis=10 WHERE Déb_semis='03-01';
UPDATE ITP SET S_semis=12 WHERE Déb_semis='03-15';
UPDATE ITP SET S_semis=14 WHERE Déb_semis='04-01';
UPDATE ITP SET S_semis=16 WHERE Déb_semis='04-15';
UPDATE ITP SET S_semis=18 WHERE Déb_semis='05-01';
UPDATE ITP SET S_semis=20 WHERE Déb_semis='05-15';
UPDATE ITP SET S_semis=23 WHERE Déb_semis='06-01';
UPDATE ITP SET S_semis=25 WHERE Déb_semis='06-15';
UPDATE ITP SET S_semis=27 WHERE Déb_semis='07-01';
UPDATE ITP SET S_semis=29 WHERE Déb_semis='07-15';
UPDATE ITP SET S_semis=31 WHERE Déb_semis='08-01';
UPDATE ITP SET S_semis=33 WHERE Déb_semis='08-15';
UPDATE ITP SET S_semis=36 WHERE Déb_semis='09-01';
UPDATE ITP SET S_semis=38 WHERE Déb_semis='09-15';
UPDATE ITP SET S_semis=40 WHERE Déb_semis='10-01';
UPDATE ITP SET S_semis=42 WHERE Déb_semis='10-15';
UPDATE ITP SET S_semis=45 WHERE Déb_semis='11-01';
UPDATE ITP SET S_semis=47 WHERE Déb_semis='11-15';
UPDATE ITP SET S_semis=49 WHERE Déb_semis='12-01';
UPDATE ITP SET S_semis=51 WHERE Déb_semis='12-15';
UPDATE ITP SET S_plantation=1 WHERE Déb_plantation='01-01';
UPDATE ITP SET S_plantation=3 WHERE Déb_plantation='01-15';
UPDATE ITP SET S_plantation=5 WHERE Déb_plantation='02-01';
UPDATE ITP SET S_plantation=7 WHERE Déb_plantation='02-15';
UPDATE ITP SET S_plantation=10 WHERE Déb_plantation='03-01';
UPDATE ITP SET S_plantation=12 WHERE Déb_plantation='03-15';
UPDATE ITP SET S_plantation=14 WHERE Déb_plantation='04-01';
UPDATE ITP SET S_plantation=16 WHERE Déb_plantation='04-15';
UPDATE ITP SET S_plantation=18 WHERE Déb_plantation='05-01';
UPDATE ITP SET S_plantation=20 WHERE Déb_plantation='05-15';
UPDATE ITP SET S_plantation=23 WHERE Déb_plantation='06-01';
UPDATE ITP SET S_plantation=25 WHERE Déb_plantation='06-15';
UPDATE ITP SET S_plantation=27 WHERE Déb_plantation='07-01';
UPDATE ITP SET S_plantation=29 WHERE Déb_plantation='07-15';
UPDATE ITP SET S_plantation=31 WHERE Déb_plantation='08-01';
UPDATE ITP SET S_plantation=33 WHERE Déb_plantation='08-15';
UPDATE ITP SET S_plantation=36 WHERE Déb_plantation='09-01';
UPDATE ITP SET S_plantation=38 WHERE Déb_plantation='09-15';
UPDATE ITP SET S_plantation=40 WHERE Déb_plantation='10-01';
UPDATE ITP SET S_plantation=42 WHERE Déb_plantation='10-15';
UPDATE ITP SET S_plantation=45 WHERE Déb_plantation='11-01';
UPDATE ITP SET S_plantation=47 WHERE Déb_plantation='11-15';
UPDATE ITP SET S_plantation=49 WHERE Déb_plantation='12-01';
UPDATE ITP SET S_plantation=51 WHERE Déb_plantation='12-15';
UPDATE ITP SET S_récolte=1 WHERE Déb_récolte='01-01';
UPDATE ITP SET S_récolte=3 WHERE Déb_récolte='01-15';
UPDATE ITP SET S_récolte=5 WHERE Déb_récolte='02-01';
UPDATE ITP SET S_récolte=7 WHERE Déb_récolte='02-15';
UPDATE ITP SET S_récolte=10 WHERE Déb_récolte='03-01';
UPDATE ITP SET S_récolte=12 WHERE Déb_récolte='03-15';
UPDATE ITP SET S_récolte=14 WHERE Déb_récolte='04-01';
UPDATE ITP SET S_récolte=16 WHERE Déb_récolte='04-15';
UPDATE ITP SET S_récolte=18 WHERE Déb_récolte='05-01';
UPDATE ITP SET S_récolte=20 WHERE Déb_récolte='05-15';
UPDATE ITP SET S_récolte=23 WHERE Déb_récolte='06-01';
UPDATE ITP SET S_récolte=25 WHERE Déb_récolte='06-15';
UPDATE ITP SET S_récolte=27 WHERE Déb_récolte='07-01';
UPDATE ITP SET S_récolte=29 WHERE Déb_récolte='07-15';
UPDATE ITP SET S_récolte=31 WHERE Déb_récolte='08-01';
UPDATE ITP SET S_récolte=33 WHERE Déb_récolte='08-15';
UPDATE ITP SET S_récolte=36 WHERE Déb_récolte='09-01';
UPDATE ITP SET S_récolte=38 WHERE Déb_récolte='09-15';
UPDATE ITP SET S_récolte=40 WHERE Déb_récolte='10-01';
UPDATE ITP SET S_récolte=42 WHERE Déb_récolte='10-15';
UPDATE ITP SET S_récolte=45 WHERE Déb_récolte='11-01';
UPDATE ITP SET S_récolte=47 WHERE Déb_récolte='11-15';
UPDATE ITP SET S_récolte=49 WHERE Déb_récolte='12-01';
UPDATE ITP SET S_récolte=51 WHERE Déb_récolte='12-15';

UPDATE ITP SET S_récolte=1 WHERE Déb_récolte ISNULL AND Fin_récolte='01-01';
UPDATE ITP SET S_récolte=3 WHERE Déb_récolte ISNULL AND Fin_récolte='01-15';
UPDATE ITP SET S_récolte=5 WHERE Déb_récolte ISNULL AND Fin_récolte='02-01';
UPDATE ITP SET S_récolte=7 WHERE Déb_récolte ISNULL AND Fin_récolte='02-15';
UPDATE ITP SET S_récolte=10 WHERE Déb_récolte ISNULL AND Fin_récolte='03-01';
UPDATE ITP SET S_récolte=12 WHERE Déb_récolte ISNULL AND Fin_récolte='03-15';
UPDATE ITP SET S_récolte=14 WHERE Déb_récolte ISNULL AND Fin_récolte='04-01';
UPDATE ITP SET S_récolte=16 WHERE Déb_récolte ISNULL AND Fin_récolte='04-15';
UPDATE ITP SET S_récolte=18 WHERE Déb_récolte ISNULL AND Fin_récolte='05-01';
UPDATE ITP SET S_récolte=20 WHERE Déb_récolte ISNULL AND Fin_récolte='05-15';
UPDATE ITP SET S_récolte=23 WHERE Déb_récolte ISNULL AND Fin_récolte='06-01';
UPDATE ITP SET S_récolte=25 WHERE Déb_récolte ISNULL AND Fin_récolte='06-15';
UPDATE ITP SET S_récolte=27 WHERE Déb_récolte ISNULL AND Fin_récolte='07-01';
UPDATE ITP SET S_récolte=29 WHERE Déb_récolte ISNULL AND Fin_récolte='07-15';
UPDATE ITP SET S_récolte=31 WHERE Déb_récolte ISNULL AND Fin_récolte='08-01';
UPDATE ITP SET S_récolte=33 WHERE Déb_récolte ISNULL AND Fin_récolte='08-15';
UPDATE ITP SET S_récolte=36 WHERE Déb_récolte ISNULL AND Fin_récolte='09-01';
UPDATE ITP SET S_récolte=38 WHERE Déb_récolte ISNULL AND Fin_récolte='09-15';
UPDATE ITP SET S_récolte=40 WHERE Déb_récolte ISNULL AND Fin_récolte='10-01';
UPDATE ITP SET S_récolte=42 WHERE Déb_récolte ISNULL AND Fin_récolte='10-15';
UPDATE ITP SET S_récolte=45 WHERE Déb_récolte ISNULL AND Fin_récolte='11-01';
UPDATE ITP SET S_récolte=47 WHERE Déb_récolte ISNULL AND Fin_récolte='11-15';
UPDATE ITP SET S_récolte=49 WHERE Déb_récolte ISNULL AND Fin_récolte='12-01';
UPDATE ITP SET S_récolte=51 WHERE Déb_récolte ISNULL AND Fin_récolte='12-15';

UPDATE ITP SET S_récolte=52 WHERE Déb_récolte ISNULL AND Fin_récolte ISNULL AND Type_culture IN('Engrais vert','Sans récolte');

UPDATE ITP SET Décal_max=1-S_plantation WHERE Fin_plantation='01-01';
UPDATE ITP SET Décal_max=3-S_plantation WHERE Fin_plantation='01-15';
UPDATE ITP SET Décal_max=5-S_plantation WHERE Fin_plantation='02-01';
UPDATE ITP SET Décal_max=7-S_plantation WHERE Fin_plantation='02-15';
UPDATE ITP SET Décal_max=10-S_plantation WHERE Fin_plantation='03-01';
UPDATE ITP SET Décal_max=12-S_plantation WHERE Fin_plantation='03-15';
UPDATE ITP SET Décal_max=14-S_plantation WHERE Fin_plantation='04-01';
UPDATE ITP SET Décal_max=16-S_plantation WHERE Fin_plantation='04-15';
UPDATE ITP SET Décal_max=18-S_plantation WHERE Fin_plantation='05-01';
UPDATE ITP SET Décal_max=20-S_plantation WHERE Fin_plantation='05-15';
UPDATE ITP SET Décal_max=23-S_plantation WHERE Fin_plantation='06-01';
UPDATE ITP SET Décal_max=25-S_plantation WHERE Fin_plantation='06-15';
UPDATE ITP SET Décal_max=27-S_plantation WHERE Fin_plantation='07-01';
UPDATE ITP SET Décal_max=29-S_plantation WHERE Fin_plantation='07-15';
UPDATE ITP SET Décal_max=31-S_plantation WHERE Fin_plantation='08-01';
UPDATE ITP SET Décal_max=33-S_plantation WHERE Fin_plantation='08-15';
UPDATE ITP SET Décal_max=36-S_plantation WHERE Fin_plantation='09-01';
UPDATE ITP SET Décal_max=38-S_plantation WHERE Fin_plantation='09-15';
UPDATE ITP SET Décal_max=40-S_plantation WHERE Fin_plantation='10-01';
UPDATE ITP SET Décal_max=42-S_plantation WHERE Fin_plantation='10-15';
UPDATE ITP SET Décal_max=45-S_plantation WHERE Fin_plantation='11-01';
UPDATE ITP SET Décal_max=47-S_plantation WHERE Fin_plantation='11-15';
UPDATE ITP SET Décal_max=49-S_plantation WHERE Fin_plantation='12-01';
UPDATE ITP SET Décal_max=51-S_plantation WHERE Fin_plantation='12-15';

UPDATE ITP SET Décal_max=1-S_semis WHERE Décal_max ISNULL AND Fin_semis='01-01';
UPDATE ITP SET Décal_max=3-S_semis WHERE Décal_max ISNULL AND Fin_semis='01-15';
UPDATE ITP SET Décal_max=5-S_semis WHERE Décal_max ISNULL AND Fin_semis='02-01';
UPDATE ITP SET Décal_max=7-S_semis WHERE Décal_max ISNULL AND Fin_semis='02-15';
UPDATE ITP SET Décal_max=10-S_semis WHERE Décal_max ISNULL AND Fin_semis='03-01';
UPDATE ITP SET Décal_max=12-S_semis WHERE Décal_max ISNULL AND Fin_semis='03-15';
UPDATE ITP SET Décal_max=14-S_semis WHERE Décal_max ISNULL AND Fin_semis='04-01';
UPDATE ITP SET Décal_max=16-S_semis WHERE Décal_max ISNULL AND Fin_semis='04-15';
UPDATE ITP SET Décal_max=18-S_semis WHERE Décal_max ISNULL AND Fin_semis='05-01';
UPDATE ITP SET Décal_max=20-S_semis WHERE Décal_max ISNULL AND Fin_semis='05-15';
UPDATE ITP SET Décal_max=23-S_semis WHERE Décal_max ISNULL AND Fin_semis='06-01';
UPDATE ITP SET Décal_max=25-S_semis WHERE Décal_max ISNULL AND Fin_semis='06-15';
UPDATE ITP SET Décal_max=27-S_semis WHERE Décal_max ISNULL AND Fin_semis='07-01';
UPDATE ITP SET Décal_max=29-S_semis WHERE Décal_max ISNULL AND Fin_semis='07-15';
UPDATE ITP SET Décal_max=31-S_semis WHERE Décal_max ISNULL AND Fin_semis='08-01';
UPDATE ITP SET Décal_max=33-S_semis WHERE Décal_max ISNULL AND Fin_semis='08-15';
UPDATE ITP SET Décal_max=36-S_semis WHERE Décal_max ISNULL AND Fin_semis='09-01';
UPDATE ITP SET Décal_max=38-S_semis WHERE Décal_max ISNULL AND Fin_semis='09-15';
UPDATE ITP SET Décal_max=40-S_semis WHERE Décal_max ISNULL AND Fin_semis='10-01';
UPDATE ITP SET Décal_max=42-S_semis WHERE Décal_max ISNULL AND Fin_semis='10-15';
UPDATE ITP SET Décal_max=45-S_semis WHERE Décal_max ISNULL AND Fin_semis='11-01';
UPDATE ITP SET Décal_max=47-S_semis WHERE Décal_max ISNULL AND Fin_semis='11-15';
UPDATE ITP SET Décal_max=49-S_semis WHERE Décal_max ISNULL AND Fin_semis='12-01';
UPDATE ITP SET Décal_max=51-S_semis WHERE Décal_max ISNULL AND Fin_semis='12-15';

UPDATE ITP SET Décal_max=Décal_max+52 WHERE Décal_max<0;

UPDATE ITP SET D_récolte=1-S_récolte WHERE Fin_récolte='01-01' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=3-S_récolte WHERE Fin_récolte='01-15' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=5-S_récolte WHERE Fin_récolte='02-01' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=7-S_récolte WHERE Fin_récolte='02-15' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=10-S_récolte WHERE Fin_récolte='03-01' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=12-S_récolte WHERE Fin_récolte='03-15' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=14-S_récolte WHERE Fin_récolte='04-01' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=16-S_récolte WHERE Fin_récolte='04-15' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=18-S_récolte WHERE Fin_récolte='05-01' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=20-S_récolte WHERE Fin_récolte='05-15' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=23-S_récolte WHERE Fin_récolte='06-01' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=25-S_récolte WHERE Fin_récolte='06-15' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=27-S_récolte WHERE Fin_récolte='07-01' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=29-S_récolte WHERE Fin_récolte='07-15' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=31-S_récolte WHERE Fin_récolte='08-01' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=33-S_récolte WHERE Fin_récolte='08-15' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=36-S_récolte WHERE Fin_récolte='09-01' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=38-S_récolte WHERE Fin_récolte='09-15' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=40-S_récolte WHERE Fin_récolte='10-01' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=42-S_récolte WHERE Fin_récolte='10-15' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=45-S_récolte WHERE Fin_récolte='11-01' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=47-S_récolte WHERE Fin_récolte='11-15' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=49-S_récolte WHERE Fin_récolte='12-01' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=51-S_récolte WHERE Fin_récolte='12-15' AND NOT(Type_culture IN('Engrais vert','Sans récolte'));

UPDATE ITP SET D_récolte=max(D_récolte-Décal_max,1) WHERE D_récolte NOTNULL AND NOT(Type_culture IN('Engrais vert','Sans récolte'));
UPDATE ITP SET D_récolte=D_récolte+52 WHERE D_récolte NOTNULL AND D_récolte<=0;

UPDATE Variétés SET S_récolte=1 WHERE Déb_récolte='01-01';
UPDATE Variétés SET S_récolte=3 WHERE Déb_récolte='01-15';
UPDATE Variétés SET S_récolte=5 WHERE Déb_récolte='02-01';
UPDATE Variétés SET S_récolte=7 WHERE Déb_récolte='02-15';
UPDATE Variétés SET S_récolte=10 WHERE Déb_récolte='03-01';
UPDATE Variétés SET S_récolte=12 WHERE Déb_récolte='03-15';
UPDATE Variétés SET S_récolte=14 WHERE Déb_récolte='04-01';
UPDATE Variétés SET S_récolte=16 WHERE Déb_récolte='04-15';
UPDATE Variétés SET S_récolte=18 WHERE Déb_récolte='05-01';
UPDATE Variétés SET S_récolte=20 WHERE Déb_récolte='05-15';
UPDATE Variétés SET S_récolte=23 WHERE Déb_récolte='06-01';
UPDATE Variétés SET S_récolte=25 WHERE Déb_récolte='06-15';
UPDATE Variétés SET S_récolte=27 WHERE Déb_récolte='07-01';
UPDATE Variétés SET S_récolte=29 WHERE Déb_récolte='07-15';
UPDATE Variétés SET S_récolte=31 WHERE Déb_récolte='08-01';
UPDATE Variétés SET S_récolte=33 WHERE Déb_récolte='08-15';
UPDATE Variétés SET S_récolte=36 WHERE Déb_récolte='09-01';
UPDATE Variétés SET S_récolte=38 WHERE Déb_récolte='09-15';
UPDATE Variétés SET S_récolte=40 WHERE Déb_récolte='10-01';
UPDATE Variétés SET S_récolte=42 WHERE Déb_récolte='10-15';
UPDATE Variétés SET S_récolte=45 WHERE Déb_récolte='11-01';
UPDATE Variétés SET S_récolte=47 WHERE Déb_récolte='11-15';
UPDATE Variétés SET S_récolte=49 WHERE Déb_récolte='12-01';
UPDATE Variétés SET S_récolte=51 WHERE Déb_récolte='12-15';

UPDATE Variétés SET D_récolte=1-S_récolte WHERE Fin_récolte='01-01';
UPDATE Variétés SET D_récolte=3-S_récolte WHERE Fin_récolte='01-15';
UPDATE Variétés SET D_récolte=5-S_récolte WHERE Fin_récolte='02-01';
UPDATE Variétés SET D_récolte=7-S_récolte WHERE Fin_récolte='02-15';
UPDATE Variétés SET D_récolte=10-S_récolte WHERE Fin_récolte='03-01';
UPDATE Variétés SET D_récolte=12-S_récolte WHERE Fin_récolte='03-15';
UPDATE Variétés SET D_récolte=14-S_récolte WHERE Fin_récolte='04-01';
UPDATE Variétés SET D_récolte=16-S_récolte WHERE Fin_récolte='04-15';
UPDATE Variétés SET D_récolte=18-S_récolte WHERE Fin_récolte='05-01';
UPDATE Variétés SET D_récolte=20-S_récolte WHERE Fin_récolte='05-15';
UPDATE Variétés SET D_récolte=23-S_récolte WHERE Fin_récolte='06-01';
UPDATE Variétés SET D_récolte=25-S_récolte WHERE Fin_récolte='06-15';
UPDATE Variétés SET D_récolte=27-S_récolte WHERE Fin_récolte='07-01';
UPDATE Variétés SET D_récolte=29-S_récolte WHERE Fin_récolte='07-15';
UPDATE Variétés SET D_récolte=31-S_récolte WHERE Fin_récolte='08-01';
UPDATE Variétés SET D_récolte=33-S_récolte WHERE Fin_récolte='08-15';
UPDATE Variétés SET D_récolte=36-S_récolte WHERE Fin_récolte='09-01';
UPDATE Variétés SET D_récolte=38-S_récolte WHERE Fin_récolte='09-15';
UPDATE Variétés SET D_récolte=40-S_récolte WHERE Fin_récolte='10-01';
UPDATE Variétés SET D_récolte=42-S_récolte WHERE Fin_récolte='10-15';
UPDATE Variétés SET D_récolte=45-S_récolte WHERE Fin_récolte='11-01';
UPDATE Variétés SET D_récolte=47-S_récolte WHERE Fin_récolte='11-15';
UPDATE Variétés SET D_récolte=49-S_récolte WHERE Fin_récolte='12-01';
UPDATE Variétés SET D_récolte=51-S_récolte WHERE Fin_récolte='12-15';

UPDATE Variétés SET D_récolte=D_récolte+52 WHERE D_récolte NOTNULL AND D_récolte<=0;

-- ALTER TABLE Espèces ADD COLUMN Densité REAL;
-- ALTER TABLE Espèces ADD COLUMN Irrig TEXT;
-- ALTER TABLE Espèces ADD COLUMN Conservation BOOL;
-- ALTER TABLE Espèces ADD COLUMN Vivace BOOL;
-- ALTER TABLE Espèces ADD COLUMN Favorable TEXT;
-- ALTER TABLE Espèces ADD COLUMN Défavorable TEXT;
-- ALTER TABLE Espèces ADD COLUMN Taille TEXT;


COMMIT TRANSACTION;
