name: Compile for macOS
on: [push]
  # workflow_dispatch:
jobs:
  Build:
    runs-on: macos-13
    steps:

      - name: Qt installation dir
        id: qt-installation-dir
        run: echo "DIR=$(pwd)/Qt" >> $GITHUB_OUTPUT

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.1.1
        with:
            cache: false
            version: 6.8.1
            host: 'mac'
            dir: '${{ steps.qt-installation-dir.DIR }}'

      - uses: actions/checkout@v4
        with:
          repository: '${{ github.repository }}'
          ref: 'main'

      - name: Debug
        shell: bash
        run: |
            ls -l $HOME/work/potaleger/
            ls -l $HOME/work/potaleger/potaleger/
            ls -l $HOME/work/potaleger/Qt/6.8.1/macos/

      - name: Build
        shell: bash
        run: |
            mkdir build
            cd build
            qmake ../potaleger.pro "QT += svg"
            make -j $(sysctl -n hw.logicalcpu)
            ls -l

      - name: Prepare artifact
        shell: bash
        run: |
            mkdir -p artifact/Potaleger.app/Contents/MacOS
            mkdir -p artifact/Potaleger.app/Contents/Frameworks
            cp -R build/potaleger.app artifact/Potaleger.app/Contents/MacOS/
            cp install/potaleger.svg artifact/Potaleger.app/
            cp install/readme.md artifact/Potaleger.app/

      - name: Deploy Qt dependencies
        shell: bash
        run: |
            macdeployqt artifact/Potaleger.app -dmg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
           name: potaleger0100macos
           path: artifact/Potaleger.dmg
