name: Compil for Linux x64
#run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Qt installation dir
        id: qt-installation-dir
        run: echo "DIR=$(readlink -f ${{ github.workspace }}/..)" >> $GITHUB_OUTPUT

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.1.1
        with:
            cache: false
            version: 6.8.1
            host: 'linux'
            dir: '${{ steps.qt-installation-dir.DIR }}'
            #setup-python: false
            #extra: '--external 7z'

      - name: Debug
        shell: bash
        run: |
            ls -l /home/runner/work/potaleger/Qt/6.8.1/gcc_64/
            ls -l /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/
            ls -l /home/runner/work/potaleger/Qt/6.8.1/gcc_64/plugins/

      - uses: actions/checkout@v4
        with:
          repository: '${{ github.repository }}'
          ref: 'main'

      - name: Build
        shell: bash
        run: |
            mkdir build
            cd build
            qmake ../potaleger.pro "QT += svg"
            make -j 4
            ls -l

      - name: Prepare artifact
        shell: bash
        run: |
            mkdir artifact
            mkdir artifact/libs
            mkdir artifact/bin
            mkdir artifact/bin/plugins
            mkdir artifact/bin/plugins/iconengines
            mkdir artifact/bin/plugins/platforminputcontexts
            mkdir artifact/bin/plugins/platforms
            mkdir artifact/bin/plugins/platformthemes
            mkdir artifact/bin/plugins/sqldrivers
            cp ./potaleger.sh ./artifact/
            cp ./build/potaleger ./artifact/bin/
            cp /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/libicu*.so* ./artifact/libs/
            cp /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/libQt6Core.so* ./artifact/libs/
            cp /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/libQt6DBus.so* ./artifact/libs/
            cp /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/libQt6Gui.so* ./artifact/libs/
            cp /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/libQt6Sql.so* ./artifact/libs/
            cp /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/libQt6Svg.so* ./artifact/libs/
            cp /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/libQt6SvgWidgets.so* ./artifact/libs/
            cp /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/libQt6Widgets.so* ./artifact/libs/
            cp /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/libQt6XcbQpa.so* ./artifact/libs/
            cp /home/runner/work/potaleger/Qt/6.8.1/gcc_64/plugins/iconengines/libqsvgicon* ./artifact/plugins/iconengines/
            cp /home/runner/work/potaleger/Qt/6.8.1/gcc_64/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so* ./artifact/plugins/platforminputcontexts/
            cp /home/runner/work/potaleger/Qt/6.8.1/gcc_64/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so* ./artifact/plugins/platforminputcontexts/
            cp /home/runner/work/potaleger/Qt/6.8.1/gcc_64/plugins/platforms/libqxcb.so* ./artifact/plugins/platforms/
            cp /home/runner/work/potaleger/Qt/6.8.1/gcc_64/plugins/platformthemes/libqgtk3.so* ./artifact/plugins/platformthemes/
            cp /home/runner/work/potaleger/Qt/6.8.1/gcc_64/plugins/platformthemes/libqxdgdesktopportal.so ./artifact/plugins/platformthemes/
            cp /home/runner/work/potaleger/Qt/6.8.1/gcc_64/plugins/sqldrivers/libqsqlite.so ./artifact/plugins/sqldrivers/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
           name: potaleger0100linux
           path: artifact
