name: Compile for Windows x64 (minGW)
on: [push]
jobs:
  Build:
    runs-on: windows-2019
    steps:

      - name: Debug
        shell: pwsh
        run: |
            Get-ChildItem -Path "D:\a\potaleger"
            Get-ChildItem -Path "D:\a\potaleger\potaleger"

      - name: Qt installation dir
        id: qt-installation-dir
        run: echo "DIR=%GITHUB_WORKSPACE%\\.." >> $GITHUB_ENV

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.1.1
        with:
            aqtversion: '==3.1.*'
            cache: false
            version: 6.8.1
            host: 'windows'
            dir: '${{ env.DIR }}'
            target: 'desktop'
            arch: 'win64_mingw'
            tools: 'tools_mingw1310'

      - name: Check MinGW Version
        shell: pwsh
        run: |
            g++ --version
            mingw32-make --version

      - uses: actions/checkout@v4
        with:
          repository: '${{ github.repository }}'
          ref: 'main'

      - name: Build
        shell: pwsh
        run: |
            mkdir build
            cd build
            qmake ..\potaleger.pro "QT += svg"
            mingw32-make

      - name: Debug
        shell: pwsh
        run: |
            #Get-ChildItem -Path "D:\a\potaleger\Qt\6.8.1\mingw_64\bin"
            Get-ChildItem -Path "D:\a\potaleger\potaleger\build\debug"
            Get-ChildItem -Path "D:\a\potaleger\potaleger\build\release"

      - name: Deploy application
        shell: pwsh
        run: |
            $QT_BIN_DIR="D:\a\potaleger\Qt\6.8.1\mingw_64\bin"
            $BUILD_DIR="D:\a\potaleger\potaleger\build\release"
            $APP_EXE="$BUILD_DIR\potaleger.exe"

            echo "Using Qt binaries from $QT_BIN_DIR"
            echo "Deploying application from $APP_EXE"

            & "$QT_BIN_DIR\windeployqt.exe" --release --compiler-runtime --verbose 0 $APP_EXE

      - name: Prepare artifact
        shell: pwsh
        run: |
            mkdir artifact
            Copy-Item -Path .\install\potaleger.svg          -Destination .\artifact\
            Copy-Item -Path .\install\readme.md              -Destination .\artifact\
            Copy-Item -Path .\build\*                        -Destination .\artifact\

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
           name: potaleger0100windows
           path: artifact
