name: Compile for Windows x64 (minGW)
on: [push]
jobs:
  Build:
    runs-on: windows-2019
    steps:
      - name: Qt installation dir
        id: qt-installation-dir
        run: echo "DIR=%GITHUB_WORKSPACE%\\.." >> $GITHUB_ENV

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.1.1
        with:
            aqtversion: '==3.1.*'
            cache: false
            version: 6.8.1
            host: 'windows'
            dir: '${{ env.DIR }}'
            target: 'desktop'
            arch: 'win64_mingw'
            tools: 'tools_mingw1310'

#      - name: Debug
#        shell: pwsh
#        run: |
#            Get-ChildItem -Path "D:\a\potaleger\Qt"
#            Get-ChildItem -Path "D:\a\potaleger\Qt\6.8.1"
#            Get-ChildItem -Path "D:\a\potaleger\Qt\6.8.1\mingw_64"
#            Get-ChildItem -Path "D:\a\potaleger\Qt\6.8.1\mingw_64\bin"

#      - name: Add Qt to PATH
#        shell: pwsh
#        run: |
#            $qtBinDir = "D:\a\potaleger\Qt\6.8.1\mingw_64\bin"
#            echo "Adding $qtBinDir to PATH"
#            [Environment]::SetEnvironmentVariable("PATH", "$env:PATH;$qtBinDir", [System.EnvironmentVariableTarget]::Process)

      - name: Check MinGW Version
        shell: pwsh
        run: |
            g++ --version
            mingw32-make --version

      - uses: actions/checkout@v4
        with:
          repository: '${{ github.repository }}'
          ref: 'main'

      - name: Build
        shell: pwsh
        run: |
            mkdir build
            cd build
            qmake ..\potaleger.pro "QT += svg"
            mingw32-make

#      - name: Display Compilation Log
#        if: failure()
#        shell: pwsh
#        run: |
#            $logFile = "build\compile.log"
#            if (Test-Path $logFile) {
#                Get-Content -Path $logFile
#            } else {
#                echo "Log file not found."
#            }

      - name: Prepare artifact
        shell: pwsh
        run: |
            mkdir artifact
            mkdir artifact\libs
            mkdir artifact\bin
            mkdir artifact\bin\plugins
            mkdir artifact\bin\plugins\iconengines
            mkdir artifact\bin\plugins\platforminputcontexts
            mkdir artifact\bin\plugins\platforms
            mkdir artifact\bin\plugins\platformthemes
            mkdir artifact\bin\plugins\sqldrivers
            Copy-Item -Path .\install\win2019\install.ps1   -Destination .\artifact\
            Copy-Item -Path .\install\win2019\potaleger.ps1 -Destination .\artifact\
            Copy-Item -Path .\install\win2019\potaleger.svg -Destination .\artifact\
            Copy-Item -Path .\install\readme.md        -Destination .\artifact\bin\
            Copy-Item -Path .\build\potaleger.exe      -Destination .\artifact\bin\
            Copy-Item -Path .\install\win2019\qt.conf -Destination .\artifact\bin\
            Copy-Item -Path $env:GITHUB_WORKSPACE\Qt\6.8.1\msvc2022_64\bin\*.dll -Destination .\artifact\libs\
            Copy-Item -Path $env:GITHUB_WORKSPACE\Qt\6.8.1\msvc2022_64\plugins\iconengines\qsvgicon.dll -Destination .\artifact\bin\plugins\iconengines\
            Copy-Item -Path $env:GITHUB_WORKSPACE\Qt\6.8.1\msvc2022_64\plugins\platforminputcontexts\composeplatforminputcontextplugin.dll -Destination .\artifact\bin\plugins\platforminputcontexts\
            Copy-Item -Path $env:GITHUB_WORKSPACE\Qt\6.8.1\msvc2022_64\plugins\platforminputcontexts\ibusplatforminputcontextplugin.dll -Destination .\artifact\bin\plugins\platforminputcontexts\
            Copy-Item -Path $env:GITHUB_WORKSPACE\Qt\6.8.1\msvc2022_64\plugins\platforms\qwindows.dll -Destination .\artifact\bin\plugins\platforms\
            Copy-Item -Path $env:GITHUB_WORKSPACE\Qt\6.8.1\msvc2022_64\plugins\platformthemes\qwindowsvistastyle.dll -Destination .\artifact\bin\plugins\platformthemes\
            Copy-Item -Path $env:GITHUB_WORKSPACE\Qt\6.8.1\msvc2022_64\plugins\sqldrivers\qsqlite.dll -Destination .\artifact\bin\plugins\sqldrivers\

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
           name: potaleger0100windows
           path: artifact
