name: Compil for Linux x64
#run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Qt installation dir
        id: qt-installation-dir
        run: echo "DIR=$(readlink -f ${{ github.workspace }}/..)" >> $GITHUB_OUTPUT
#      - name: Install Qt
#        uses: jurplel/install-qt-action@v4
#        with:
#            cache: true
#            version: 6.8.1
#            host: 'linux'
#            dir: '${{ steps.qt-installation-dir.DIR }}'
#            #setup-python: 'false'
#            #extra: '--external 7z'
      #- name: Clone repo
      - uses: actions/checkout@v4
        with:
          repository: '${{ github.repository }}'
          ref: 'main'
      - run: ls -l
      - run: mkdir install
      - run: cd install
      - run: ls -l
      - run: qmake ../potaleger.pro "QT += svg"
      - run: make -j 4
      - run: ls -l

      - run: echo "This job's status is ${{ job.status }}."
